### ISSUE TITLE
Cleaning of branches

### ISSUE THREAD

**Issue by Neustradamus** [ipasimulator/ipasim#13]
Dear @ipasimulator team, @jjonescz,

It is possible to remove merged branches?
- https://github.com/ipasimulator/ipasim/branches/all

Thanks in advance.

**Comment by jjonescz** [comment]
Hm, I'm curious why you are interested in that? Do old branches cause some issues?

Even merged branches might provide some info - they are effectively tagging commits (for example where development of one feature ended - in particular because this repo didn't use PRs for that previously as I was the only developer) - I could perhaps convert those old branches to tags, though, or just note the branch names and corresponding commit hashes somewhere.

**Comment by Neustradamus** [comment]
A lot of branches...

Tags are here:
- https://github.com/ipasimulator/ipasim/tags

**Comment by jjonescz** [comment]
> A lot of branches...

They are all very old and effectively abandoned now, so feel free to just ignore them 😀. Except `master` where the occasional updates happen.

When there's more development in this repo and we use more branches, surely we can delete the old ones then.

**Comment by Neustradamus** [comment]
Maybe you can do a cleaning, it is my original request...

**Comment by jjonescz** [comment]
Okay, I guess why not. Removed old branches.

Here's a backup:

- `backup`: 64a29b3: build succeeds now
- `build_patch_cmake`: 6895798: [build] Patched CMake.
- `build_rc_script`: b4b8a14: [build] Installed `rc.exe` shim for `rc.cmd`.
- `build_release`: 6086fc9: [uwp] Log method name in `dumpAddr`
- `cg_got_clang_ctx`: b5971ce: [cg] Got (rather than created) `ClangCtx`.
- `cg_objc_categories`: 1f9c8cc: [cg] Add DLL name to wrapper names
- `cg_ref_symbol`: 13269a1: [cg] Use `_mh_dylib_header` as reference symbol
- `copy_objc`: 8961885: Merge branch 'master' into copy_objc
- `deps_building_tapi`: 64894df: [deps] Trying to build `tapi` (backup).
- `develop`: 352988f: [config] Update certificate
- `develop_old`: 42f61a7: [uwp] Use `DynamicBackCaller`
- `dyld_crt_init`: d5ab9f3: [dyld] Initialized C++ runtime manually (backup).
- `feature_mmap`: b91a93d: [uwp] Unmap the binary after parsing
- `master`: f616174: Add SampleGame source code
- `master_old`: 1df6f9d: [pthread] Exclude `COPYING.LIB` from Git LFS
- `pep_header_asm`: b2295be: [pep] Added the `.mhdr` section in an `.asm` file (backup).
- `thesis`: 16729d2: [build] Add script `extract.ps1`
- `thesis_old`: 16aedea: [pthread] Exclude `COPYING.LIB` from Git LFS
- `use_retdec`: c25b419: retdec referenced from HeadersAnalyzer (backup)
- `uwp_jumpBack`: 740ba33: [uwp] Try to use `ipaSim_jumpBack`
- `uwp_memory_mapping`: d6ad919: [uwp] Try to implement memory-mapping

**Comment by Neustradamus** [comment]
@jjonescz: Thanks :)

Do not hesitate to create a fork in your personal account and use it before merging in develop or master upstream ^^
