### ISSUE TITLE
After opened, it crashs immediately on Win10 1809 build 17763.557(build-v1.0)

### ISSUE THREAD

**Issue by JyerZ** [ipasimulator/ipasim#2]
As mentioned above, so there aren't any screenshots.

I'm going to try building the project by using partially prebuilt artifacts, but it seems that your docker images don't have any TAGS, or even the repository itself seems doesn't exist?
![pull error](https://user-images.githubusercontent.com/18640984/61438698-a1f40300-a972-11e9-8873-ca3ecf899442.png)

Finally, I can only try to build the project from sources. One question, what's the reason for using docker of Windows container instead of Windows host while building from sources? Or, Is there any way to build from sources on Windows host instead of using docker?

By the way, on Win10 1903, it occurs the same issue as #1

**Comment by jjonescz** [comment]
The repository didn't have any tags because the CI build that creates them was failing. I fixed it, so you should be able to build the project from prebuilt artifacts.

The reason for using Docker is because lots of dependencies are needed for the build to work and the building context is sensitive to changes. So, by using Docker, the building process is ensured to be deterministic.

If you manage to build the project, please debug the crash and report the error here.

**Comment by JyerZ** [comment]
> The repository didn't have any tags because the CI build that creates them was failing. I fixed it, so you should be able to build the project from prebuilt artifacts.
> The reason for using Docker is because lots of dependencies are needed for the build to work and the building context is sensitive to changes. So, by using Docker, the building process is ensured to be deterministic.
> If you manage to build the project, please debug the crash and report the error here.

OK, I built the project with prebuilt artifacts successfully. 
But it can't get the crash occurred again on 1809 version, either the DEBUG prebuilt artifacts and app, or the RELEASE things. Instead, it occurred the same issue (on 1809 version) as #1, both DEBUG and RELEASE.
Finally, I uninstall the app built by myself and install your build-v1.0 again (on 1809 version). It run the three samples successfully without any load error in mach-o dylibs and win32pe dlls. 
It's so strange......

**Comment by jjonescz** [comment]
Thank you for your help. I've investigated more on your original issue and found out its cause. It occurs because some of the DLLs depend on `msvcp140.dll` and `vcruntime140.dll`. These are part of Visual C++ (see [Microsoft Docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-library-features?view=vs-2017) for more details) which you probably didn't have installed (or not the right version). 

Ideally, the emulator shouldn't depend on these DLLs and instead use their `*_app.dll` versions which are avilable for UWP apps. I will try to fix it, but in the meantime, the workaround is to install [Visual C++ Redistributable 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) (the x86 version). You probably did that (maybe indirectly by installing Visual Studio), so the original issue disappeared for you.

As for your current issue, I will investigate further and report any progress at #1.
