### ISSUE TITLE
certificate expired

### ISSUE THREAD

**Issue by ConnorDoesDev** [ipasimulator/ipasim#7]
the certificate expired almost two years ago.

**Comment by jjonescz** [comment]
You should be able to renew it yourself&mdash;see #4, #3. Otherwise, I will update it later.

**Comment by jjonescz** [comment]
I have updated the certificate: <https://github.com/ipasimulator/ipasim/releases/download/v1.0.1/ipasim-build-v1.0.1-2022-04-27.zip>. If it still does not work, please let me know.

**Comment by jjonescz** [comment]
That's a good idea, will investigate.

**Comment by upintheairsheep** [comment]
I have a suggestion, you should get in touch with Jason Nieh and tell him to finally release Cycada's source code to the public, although your two methods are different, you guys both share the same goal. I contacted every team member in every possible method I've got, and got zero replies, and it seems the emails were not delivered to the columbia email addresses, and needs a work email. The only response I got, by Dall (contacting him on his github email adress that is personal) told me that it is closed source code changes so we can't release it, and rudely said that you should expect no reply. That's a rude way to end a conversation. Anyways, we should tell Mr. Nieh to release the code, and use diff ed scripts, which contain only your code, and does not contain any of the original code at all, and use a script to patch the closed source code only when provided. Since Cycada is so old, it won't effect iPhone sales at all, if you exclude used vintage iPhones from eBay. I have a dream to preserve iOS apps for tomorrow's generations.

**Comment by upintheairsheep** [comment]
It would also be fun to see the an animated screenshot of the infamous I am Rich app running on ipasim as a screenshot demonstrating the support for commercial apps.

https://archive.org/download/iOSObscura/iPhoneOS%202/9C48YYZAC5.IAmRich/I%20Am%20Rich-%289C48YYZAC5.IAmRich%29-1.0-%28iOS_2.0%29-32e42b8d33477a06aa0d1b8470318617.ipa

**Comment by jjonescz** [comment]
@upintheairsheep it doesn't seem the certificate is expired now. Have you downloaded the latest update https://github.com/ipasimulator/ipasim/releases/download/v1.0.1/ipasim-build-v1.0.1-2022-04-27.zip? It should be valid one year, i.e., until 2023-04-27.

**Comment by upintheairsheep** [comment]
> @upintheairsheep it doesn't seem the certificate is expired now. Have you downloaded the latest update https://github.com/ipasimulator/ipasim/releases/download/v1.0.1/ipasim-build-v1.0.1-2022-04-27.zip? It should be valid one year, i.e., until 2023-04-27.
> 
> I have also added a GitHub Action to renew the certificate automatically.

Ok thanks, I just installed it the wrong way, but make sure to make a GitHub action to renew it
